name: 'Slatify'
description: 'Slack Notification for Github Actions'
author: 'homoluctus'
inputs:
  channel:
    description: 'slack channel'
    required: false
    default: '#general'
  url:
    description: 'slack incoming webhook url'
    required: true
  created_tag: 
    description: 'created tag for release'
    required: true 
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: 'green'
