name: 'Slatify'
description: 'Slack Notification for Github Actions'
author: 'homoluctus'
inputs:
  channel:
    description: 'slack channel'
    required: false
  url:
    description: 'slack incoming webhook url'
    required: false
  created_tag: 
      description: 'created tag for release'
      required: false 
  changelog_file:
      description: 'change lig file'
      required: false 
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: 'green'